-- NCAE - check for NCAESettings and only let the animations get through that are set to false
local cameraAnimationFilePaths={}

if not NCAESettings.nukeAnimation_CQCThrows then
  table.insert(cameraAnimationFilePaths, {name="CqcStandThrowFront",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_thw_s_com_f_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_thw_s_com_f_02.cani"},recoverPreOrientation=false})
  table.insert(cameraAnimationFilePaths, {name="CqcStandThrowBack",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_thw_s_com_b_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_thw_s_com_b_02.cani"},recoverPreOrientation=false})
  table.insert(cameraAnimationFilePaths, {name="CqcStandThrowRight",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_thw_s_com_r_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_thw_s_com_r_02.cani"},recoverPreOrientation=false})
  table.insert(cameraAnimationFilePaths, {name="CqcStandThrowLeft",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_thw_s_com_l_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_thw_s_com_l_02.cani"},recoverPreOrientation=false})
  table.insert(cameraAnimationFilePaths, {name="CqcBehindThrowStandFrontLeft",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_beh_l_thw_ef_01.cani"}})
  table.insert(cameraAnimationFilePaths, {name="CqcBehindThrowStandFrontRight",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_beh_r_thw_ef_01.cani"}})
  table.insert(cameraAnimationFilePaths, {name="CqcBehindThrowStandBackLeft",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_beh_l_thw_eb_01.cani"}})
  table.insert(cameraAnimationFilePaths, {name="CqcBehindThrowStandBackRight",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_beh_r_thw_eb_01.cani"}})
  table.insert(cameraAnimationFilePaths, {name="CqcBehindThrowSquatFrontLeft",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_q_beh_l_thw_ef_01.cani"}})
  table.insert(cameraAnimationFilePaths, {name="CqcBehindThrowSquatFrontRight",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_q_beh_r_thw_ef_01.cani"}})
  table.insert(cameraAnimationFilePaths, {name="CqcBehindThrowSquatBackLeft",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_q_beh_l_thw_eb_01.cani"}})
  table.insert(cameraAnimationFilePaths, {name="CqcBehindThrowSquatBackRight",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_q_beh_r_thw_eb_01.cani"}})
  table.insert(cameraAnimationFilePaths, {name="CqcBehindCovetThrowSquatLeft",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_q_lbh_l_thw_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_q_lbh_l_thw_02.cani"}})
  table.insert(cameraAnimationFilePaths, {name="CqcBehindCovetThrowSquatRight",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_q_lbh_r_thw_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_q_lbh_r_thw_02.cani"}})
  table.insert(cameraAnimationFilePaths, {name="CqcSeizeThrowFront",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_cke_nea_thw_f_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_cke_nea_thw_f_02.cani"},recoverPreOrientation=false})
  table.insert(cameraAnimationFilePaths, {name="CqcSeizeThrowBack",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_cke_nea_thw_b_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_cke_nea_thw_b_02.cani"},recoverPreOrientation=false})
  table.insert(cameraAnimationFilePaths, {name="CqcLadderFront",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_lad_r_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_lad_r_02.cani"}})
  table.insert(cameraAnimationFilePaths, {name="CqcLadderBack",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_lad_l_b_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_lad_l_b_02.cani"}})
end

if not NCAESettings.nukeAnimation_CQCDisarm then
  table.insert(cameraAnimationFilePaths, {name="CqcSnatchAssaultLeft",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_hld_asr_f_01.cani"},recoverPreOrientation=false})
  table.insert(cameraAnimationFilePaths, {name="CqcSnatchAssaultRight",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_hld_asr_f_02.cani"},recoverPreOrientation=false})
end

if not NCAESettings.nukeAnimation_CQCCombos then
  table.insert(cameraAnimationFilePaths, {name="CqcComboFinishFront",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_new_com_asr_f5_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_new_com_asr_f5_02.cani"},recoverPreOrientation=false})
  table.insert(cameraAnimationFilePaths, {name="CqcComboFinishBack",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_new_com_asr_b3_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_new_com_asr_b3_02.cani"},recoverPreOrientation=false})
end

if not NCAESettings.nukeAnimation_CQCCounterAtt then
  table.insert(cameraAnimationFilePaths, {name="CounterToKnife",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_cnt_knf_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_cnt_knf_02.cani"}})
  table.insert(cameraAnimationFilePaths, {name="CounterToGunStrike",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_cnt_gun_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_cqc/gcam_cqc_s_cnt_gun_02.cani"}})
  table.insert(cameraAnimationFilePaths, {name="CounterToLiquidAttack1",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_lqd/gcam_cqc_s_cnt1_com1_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_lqd/gcam_cqc_s_cnt1_com1_02.cani"},recoverPreOrientation=false,ignoreCollisionCheckOnStart=true,stopPlayingByCollision=false,keepPosition=true})
  table.insert(cameraAnimationFilePaths, {name="CounterToLiquidAttack2",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_lqd/gcam_cqc_s_cnt1_com2_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_lqd/gcam_cqc_s_cnt1_com2_02.cani"},recoverPreOrientation=false,ignoreCollisionCheckOnStart=true,stopPlayingByCollision=false,keepPosition=true})
  table.insert(cameraAnimationFilePaths, {name="CounterToLiquidJumpAttack",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_lqd/gcam_lqd_s_cnt3_jmp_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_lqd/gcam_lqd_s_cnt3_jmp_02.cani"},recoverPreOrientation=false,ignoreCollisionCheckOnStart=true,stopPlayingByCollision=false,keepPosition=true})
  table.insert(cameraAnimationFilePaths, {name="CounterToLiquidStrike",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_lqd/gcam_cqc_s_cnt3_tuki_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_lqd/gcam_cqc_s_cnt3_tuki_02.cani"},recoverPreOrientation=false,ignoreCollisionCheckOnStart=true,stopPlayingByCollision=false,keepPosition=true})
  table.insert(cameraAnimationFilePaths, {name="CounterToParasiteFogMacheteA",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_wmu/gcam_wmu_s_cnt_lm_set_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_wmu/gcam_wmu_s_cnt_lm_set_02.cani"},recoverPreOrientation=false,ignoreCollisionCheckOnStart=true,stopPlayingByCollision=false,keepPosition=true})
  table.insert(cameraAnimationFilePaths, {name="CounterToParasiteFogMacheteB",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_wmu/gcam_wmu_s_cnt_ru_set_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_wmu/gcam_wmu_s_cnt_ru_set_02.cani"},recoverPreOrientation=false,ignoreCollisionCheckOnStart=true,stopPlayingByCollision=false,keepPosition=true})
  table.insert(cameraAnimationFilePaths, {name="CounterToParasiteCommonMachete",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_wmu/gcam_wmu_s_cnt_f_set_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_wmu/gcam_wmu_s_cnt_f_set_02.cani"},recoverPreOrientation=false,ignoreCollisionCheckOnStart=true,stopPlayingByCollision=false,keepPosition=true})
  table.insert(cameraAnimationFilePaths, {name="CounterToParasiteHardMacheteA",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_wmu/gcam_wmu3_s_cnt_rd_set_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_wmu/gcam_wmu3_s_cnt_rd_set_02.cani"},recoverPreOrientation=false,ignoreCollisionCheckOnStart=true,stopPlayingByCollision=false,keepPosition=true})
  table.insert(cameraAnimationFilePaths, {name="CounterToParasiteHardMacheteB",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_wmu/gcam_wmu3_s_cnt_lu_set_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_wmu/gcam_wmu3_s_cnt_lu_set_02.cani"},recoverPreOrientation=false,ignoreCollisionCheckOnStart=true,stopPlayingByCollision=false,keepPosition=true})
  table.insert(cameraAnimationFilePaths, {name="CounterToParasiteCmoufMacheteA",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_wmu/gcam_wmu1_s_cnt_rm_set_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_wmu/gcam_wmu1_s_cnt_rm_set_02.cani"},recoverPreOrientation=false,ignoreCollisionCheckOnStart=true,stopPlayingByCollision=false,keepPosition=true})
  table.insert(cameraAnimationFilePaths, {name="CounterToParasiteCmoufMacheteB",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_wmu/gcam_wmu1_s_cnt_ld_set_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_wmu/gcam_wmu1_s_cnt_ld_set_02.cani"},recoverPreOrientation=false,ignoreCollisionCheckOnStart=true,stopPlayingByCollision=false,keepPosition=true})
end

if not NCAESettings.nukeAnimation_cureWounds then
  table.insert(cameraAnimationFilePaths, {name="CureGunShotWoundBodyLeft",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cue/gcam_cue_q_bdy_cue_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_cue/gcam_cue_q_bdy_cue_02.cani"}})
  table.insert(cameraAnimationFilePaths, {name="CureGunShotWoundBodyRight",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cue/gcam_cue_q_bdy_cue_r_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_cue/gcam_cue_q_bdy_cue_r_02.cani"}})
  table.insert(cameraAnimationFilePaths, {name="CureGunShotWoundBodyCrawl",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cue/gcam_cue_c_bdy_cue_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_cue/gcam_cue_c_bdy_cue_02.cani"}})
  table.insert(cameraAnimationFilePaths, {name="CureGunShotWoundBodySupine",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cue/gcam_cue_p_bdy_cue_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_cue/gcam_cue_p_bdy_cue_02.cani"}})
  table.insert(cameraAnimationFilePaths, {name="CureArmDislocationStand",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cue/gcam_cue_s_arm_cue_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_cue/gcam_cue_s_arm_cue_02.cani"}})
  table.insert(cameraAnimationFilePaths, {name="CureArmDislocationSquat",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cue/gcam_cue_q_arm_cue_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_cue/gcam_cue_q_arm_cue_02.cani"}})
  table.insert(cameraAnimationFilePaths, {name="CureFootDislocation",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_cue/gcam_cue_s_leg_cue_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_cue/gcam_cue_s_leg_cue_02.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_cue/gcam_cue_s_leg_cue_03.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_cue/gcam_cue_s_leg_cue_04.cani"}})
end

if not NCAESettings.nukeAnimation_horse then
  table.insert(cameraAnimationFilePaths, {name="RideOnHorseFrontRight",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_02.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_03.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_04.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_05.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_06.cani"},recoverPreOrientation=true,keepPosition=false,interpTimeAfterFinishingToKeepPosition=2})
  table.insert(cameraAnimationFilePaths, {name="RideOnHorseSideRight",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_02.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_03.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_04.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_05.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_06.cani"},recoverPreOrientation=true,keepPosition=false,interpTimeAfterFinishingToKeepPosition=2})
  table.insert(cameraAnimationFilePaths, {name="RideOnHorseBackRight",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_02.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_03.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_04.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_05.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_06.cani"},recoverPreOrientation=true,keepPosition=false,interpTimeAfterFinishingToKeepPosition=2})
  table.insert(cameraAnimationFilePaths, {name="RideOnHorseFrontLeft",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_02.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_03.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_04.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_05.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_06.cani"},recoverPreOrientation=true,keepPosition=false,interpTimeAfterFinishingToKeepPosition=2})
  table.insert(cameraAnimationFilePaths, {name="RideOnHorseSideLeft",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_02.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_03.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_04.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_05.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_06.cani"},recoverPreOrientation=true,keepPosition=false,interpTimeAfterFinishingToKeepPosition=2})
  table.insert(cameraAnimationFilePaths, {name="RideOnHorseBackLeft",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_02.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_03.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_04.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_05.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_06.cani"},recoverPreOrientation=true,keepPosition=false,interpTimeAfterFinishingToKeepPosition=2})
  table.insert(cameraAnimationFilePaths, {name="RideOnHorseRun",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_rn_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_rideon_rn_02.cani"},recoverPreOrientation=true,keepPosition=false,interpTimeAfterFinishingToKeepPosition=2})
  table.insert(cameraAnimationFilePaths, {name="PlaceBearersHorseLeft",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_ene_l_st_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_ene_l_st_02.cani"},recoverPreOrientation=true,keepPosition=false,interpTimeAfterFinishingToKeepPosition=2})
  table.insert(cameraAnimationFilePaths, {name="PlaceBearersHorseRight",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_ene_r_st_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_ene_r_st_02.cani"},recoverPreOrientation=true,keepPosition=false,interpTimeAfterFinishingToKeepPosition=2})
  table.insert(cameraAnimationFilePaths, {name="LowerBearersHorseLeft",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_ene_l_ed_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_ene_l_ed_02.cani"},recoverPreOrientation=true,keepPosition=false,interpTimeAfterFinishingToKeepPosition=2})
  table.insert(cameraAnimationFilePaths, {name="LowerBearersHorseRight",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_ene_r_ed_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_adsn/gcam_adsn_ene_r_ed_02.cani"},recoverPreOrientation=true,keepPosition=false,interpTimeAfterFinishingToKeepPosition=2})
end

if not NCAESettings.nukeAnimation_walker then
  table.insert(cameraAnimationFilePaths, {name="RideOnWalkerGear",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_wkg/gcam_wkg_s_tak_on_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_wkg/gcam_wkg_s_tak_on_02.cani"},isRiding=true})
  table.insert(cameraAnimationFilePaths, {name="CarryAtWalkerGear",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_wkg/gcam_wkc_s_p_st_f_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_wkg/gcam_wkc_s_p_st_f_02.cani"},isRiding=true,recoverPreOrientation=true,keepPosition=false})
end

if not NCAESettings.nukeAnimation_CQCwalker then
  table.insert(cameraAnimationFilePaths, {name="WalkerGearCQCStand",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_wkg/gcam_s_cke_st_wg_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_wkg/gcam_s_cke_st_wg_02.cani"},recoverPreOrientation=true,keepPosition=false})
  table.insert(cameraAnimationFilePaths, {name="WalkerGearCQCSquat",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_wkg/gcam_q_cke_st_wg_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_wkg/gcam_q_cke_st_wg_02.cani"},recoverPreOrientation=true,keepPosition=false})
end

if not NCAESettings.nukeAnimation_vehicles then
  table.insert(cameraAnimationFilePaths, {name="RideOnVehicle",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_plv/gcam_plv_s_rde_st_r_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_plv/gcam_plv_s_rde_st_r_02.cani"},isRiding=true})
  table.insert(cameraAnimationFilePaths, {name="RideOnVehicleFromAssistantDriversSeat",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_plv/gcam_plv_s_rde_sid_st_l_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_plv/gcam_plv_s_rde_sid_st_l_02.cani"},isRiding=true})
  table.insert(cameraAnimationFilePaths, {name="PlaceBearersVehicleToAssistantDriversSeat",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_plv/gcam_plv_sid_st_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_plv/gcam_plv_sid_st_02.cani"},ignoreCollisionCheckOnPlaying=true,ignoreCollisionCheckOnStart=true,isRiding=true})
  table.insert(cameraAnimationFilePaths, {name="LowerBearersVehicleFromAssistantDriversSeat",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_plv/gcam_plv_sid_ed_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_plv/gcam_plv_sid_ed_02.cani"},ignoreCollisionCheckOnPlaying=true,ignoreCollisionCheckOnStart=true,isRiding=true})
  table.insert(cameraAnimationFilePaths, {name="PlaceBearersVehicleFromLeftSideToRearSeatLeft",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_plv/gcam_plv_rel_st_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_plv/gcam_plv_rel_st_02.cani"},ignoreCollisionCheckOnPlaying=true,ignoreCollisionCheckOnStart=true,isRiding=true})
  table.insert(cameraAnimationFilePaths, {name="LowerBearersVehicleFromLeftSideToRearSeatLeft",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_plv/gcam_plv_rel_ed_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_plv/gcam_plv_rel_ed_02.cani"},ignoreCollisionCheckOnPlaying=true,ignoreCollisionCheckOnStart=true,isRiding=true})
  table.insert(cameraAnimationFilePaths, {name="PlaceBearersVehicleFromRightSideToRearSeatRight",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_plv/gcam_plv_rer_st_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_plv/gcam_plv_rer_st_02.cani"},ignoreCollisionCheckOnPlaying=true,ignoreCollisionCheckOnStart=true,isRiding=true})
  table.insert(cameraAnimationFilePaths, {name="LowerBearersVehicleFromRightSideToRearSeatRight",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_plv/gcam_plv_rer_ed_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_plv/gcam_plv_rer_ed_02.cani"},ignoreCollisionCheckOnPlaying=true,ignoreCollisionCheckOnStart=true,isRiding=true})
  table.insert(cameraAnimationFilePaths, {name="PlaceBearersVehicleFromBackToRearSeatRight",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_plv/gcam_plv_reb_r_st_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_plv/gcam_plv_reb_r_st_02.cani"},ignoreCollisionCheckOnPlaying=true,ignoreCollisionCheckOnStart=true,isRiding=true})
  table.insert(cameraAnimationFilePaths, {name="LowerBearersVehicleFromBackToRearSeatRight",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_plv/gcam_plv_reb_r_ed_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_plv/gcam_plv_reb_r_ed_02.cani"},ignoreCollisionCheckOnPlaying=true,ignoreCollisionCheckOnStart=true,isRiding=true})
  table.insert(cameraAnimationFilePaths, {name="PlaceBearersVehicleFromBackToRearSeatLeft",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_plv/gcam_plv_reb_l_st_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_plv/gcam_plv_reb_l_st_02.cani"},ignoreCollisionCheckOnPlaying=true,ignoreCollisionCheckOnStart=true,isRiding=true})
  table.insert(cameraAnimationFilePaths, {name="LowerBearersVehicleFromBackToRearSeatLeft",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_plv/gcam_plv_reb_l_ed_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_plv/gcam_plv_reb_l_ed_02.cani"},ignoreCollisionCheckOnPlaying=true,ignoreCollisionCheckOnStart=true,isRiding=true})
  table.insert(cameraAnimationFilePaths, {name="RideOnTruck",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_nmt/gcam_nmt_s_rde_drv_st_l_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_nmt/gcam_nmt_s_rde_drv_st_l_02.cani"},isRiding=true})
  table.insert(cameraAnimationFilePaths, {name="RideOnTruckFromAssistantDriversSeat",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_nmt/gcam_nmt_s_rde_sid2_st_l_02.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_nmt/gcam_nmt_s_rde_sid2_st_l_01.cani"},isRiding=true})
  table.insert(cameraAnimationFilePaths, {name="PlaceBearersTruckFromLeftSideToRearSeatLeft",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_nmt/gcam_nmt_sid_st_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_nmt/gcam_nmt_sid_st_02.cani"},ignoreCollisionCheckOnPlaying=true,ignoreCollisionCheckOnStart=true,isRiding=true})
  table.insert(cameraAnimationFilePaths, {name="LowerBearersTruckFromBackToRearSeatRight",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_nmt/gcam_nmt_sid_ed_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_nmt/gcam_nmt_sid_ed_02.cani"},ignoreCollisionCheckOnPlaying=true,ignoreCollisionCheckOnStart=true,isRiding=true})
  table.insert(cameraAnimationFilePaths, {name="RideOnArmoredVehicleWest",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_wav/gcam_wav_s_rid_on_l_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_wav/gcam_wav_s_rid_on_l_02.cani"},recoverPreOrientation=false,keepPosition=true,isRiding=true})
  table.insert(cameraAnimationFilePaths, {name="RideOnArmoredVehicleEast",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_wav/gcam_sav_s_rid_on_l_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_wav/gcam_sav_s_rid_on_l_02.cani"},recoverPreOrientation=false,keepPosition=true,isRiding=true})
end

if not NCAESettings.nukeAnimation_helicopterRides then
  table.insert(cameraAnimationFilePaths, {name="RideOnHelicopter",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_uth/gcam_uth_q_rid_pos_l_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_uth/gcam_uth_q_rid_pos_l_02.cani"},isRiding=true,recoverPreOrientation=false,keepPosition=true})
  table.insert(cameraAnimationFilePaths, {name="GiveCharaterRideHelicopter",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_uth/gcam_cry_s_ene_uth_dwn_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_uth/gcam_cry_s_ene_uth_dwn_02.cani"},isRiding=true})
  table.insert(cameraAnimationFilePaths, {name="GiveCharaterRideHelicopterAndRideOn",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_uth/gcam_cry_s_ene_uth_dwn_sit_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_uth/gcam_cry_s_ene_uth_dwn_sit_02.cani"},isRiding=true,recoverPreOrientation=false,keepPosition=true})
  table.insert(cameraAnimationFilePaths, {name="MissionStartOnHeli",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_heli/gcam_heri_start_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_heli/gcam_heri_start_02.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_heli/gcam_heri_start_03.cani"},isRiding=true,recoverPreOrientation=false,keepPosition=true,interpTimeAfterFinishingToKeepPosition=2})
  table.insert(cameraAnimationFilePaths, {name="MissionStartOnHeli2",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_heli/gcam_heri_start_04.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_heli/gcam_heri_start_05.cani"},isRiding=true,recoverPreOrientation=false,keepPosition=true,interpTimeAfterFinishingToKeepPosition=2})
  table.insert(cameraAnimationFilePaths, {name="MissionStartOnHeli3",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_heli/gcam_heri_start_06.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_heli/gcam_heri_start_07.cani"},isRiding=true,recoverPreOrientation=false,keepPosition=true,interpTimeAfterFinishingToKeepPosition=2})
end

if not NCAESettings.nukeAnimation_objects then
  table.insert(cameraAnimationFilePaths, {name="GoInsideCBox",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_box/gcam_box_s_sup_in_01.cani"},recoverPreOrientation=false,ignoreCollisionCheckOnStart=true,stopPlayingByCollision=false,keepPosition=true})
  table.insert(cameraAnimationFilePaths, {name="GoInsideTrashBox",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_tsh/gcam_tsh_s_st_01.cani"},recoverPreOrientation=false,ignoreCollisionCheckOnStart=false,ignoreCollisionCheckOnPlaying=false,keepPosition=true})
  table.insert(cameraAnimationFilePaths, {name="GetOutTrashBox",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_tsh/gcam_tsh_s_ed_01.cani"},recoverPreOrientation=false,ignoreCollisionCheckOnStart=false,ignoreCollisionCheckOnPlaying=false,isEnableAtAnyCameras=true})
  table.insert(cameraAnimationFilePaths, {name="CqcDragToTrashBox",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_tsh/gcam_cqc_tsh_q_l_cke_ef_01.cani"},recoverPreOrientation=false,ignoreCollisionCheckOnStart=false,ignoreCollisionCheckOnPlaying=false,isEnableAtAnyCameras=true,keepPosition=true})
  table.insert(cameraAnimationFilePaths, {name="GoInsideTrashBoxCarryBoth",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_tsh/gcam_tsh_s_cry_ed1_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_tsh/gcam_tsh_s_cry_ed1_02.cani"},recoverPreOrientation=false,ignoreCollisionCheckOnStart=false,ignoreCollisionCheckOnPlaying=false,isEnableAtAnyCameras=true,keepPosition=true})
  table.insert(cameraAnimationFilePaths, {name="GoInsideTrashBoxCarry",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_tsh/gcam_tsh_s_cry_ed2_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_tsh/gcam_tsh_s_cry_ed2_02.cani"},recoverPreOrientation=false,ignoreCollisionCheckOnStart=false,ignoreCollisionCheckOnPlaying=false,isEnableAtAnyCameras=true,keepPosition=true})
  table.insert(cameraAnimationFilePaths, {name="GetOutTrashBoxCarry",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_tsh/gcam_tsh_s_cry_st_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_tsh/gcam_tsh_s_cry_st_02.cani"},recoverPreOrientation=false,ignoreCollisionCheckOnStart=false,ignoreCollisionCheckOnPlaying=false,isEnableAtAnyCameras=true,keepPosition=true})
  table.insert(cameraAnimationFilePaths, {name="GoInsideToilet",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_tle/gcam_tle_s_in_01.cani"},recoverPreOrientation=true,ignoreCollisionCheckOnStart=true,ignoreCollisionCheckOnPlaying=true,isEnableAtAnyCameras=true})
  table.insert(cameraAnimationFilePaths, {name="GoInsideToiletCarryBoth",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_tle/gcam_tle_s_cry_ed1_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_tle/gcam_tle_s_cry_ed1_02.cani"},recoverPreOrientation=true,ignoreCollisionCheckOnStart=true,ignoreCollisionCheckOnPlaying=true,isEnableAtAnyCameras=true})
  table.insert(cameraAnimationFilePaths, {name="CloseToiletDoor",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_tle/gcam_tle_s_cry_ed2_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_tle/gcam_tle_s_cry_ed2_02.cani"},recoverPreOrientation=true,ignoreCollisionCheckOnStart=true,ignoreCollisionCheckOnPlaying=true,isEnableAtAnyCameras=true})
  table.insert(cameraAnimationFilePaths, {name="TakeOutFromToilet",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_tle/gcam_tle_s_cry_s_01.cani"},recoverPreOrientation=true,ignoreCollisionCheckOnStart=true,ignoreCollisionCheckOnPlaying=true,isEnableAtAnyCameras=true})
  table.insert(cameraAnimationFilePaths, {name="GoInsideShower",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_swer/gcam_swer_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_swer/gcam_swer_02.cani"},recoverPreOrientation=true,ignoreCollisionCheckOnStart=true,ignoreCollisionCheckOnPlaying=true,isEnableAtAnyCameras=true})
end

if not NCAESettings.nukeAnimation_climbing then
  table.insert(cameraAnimationFilePaths, {name="StartCliffClimb",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_clf/gcam_clf_90_vtcl_st_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_clf/gcam_clf_90_vtcl_st_02.cani"},recoverPreOrientation=false,isEnableAtAnyCameras=true,keepPosition=true})
end

if not NCAESettings.nukeAnimation_animalsAtt then
  table.insert(cameraAnimationFilePaths, {name="WolfAttackStandFront",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_wlf/gcam_wlf_s_atk_st_f_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_wlf/gcam_wlf_s_atk_st_f_02.cani"},recoverPreOrientation=false,isEnableAtAnyCameras=true,keepPosition=false})
  table.insert(cameraAnimationFilePaths, {name="WolfAttackStandBack",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_wlf/gcam_wlf_s_atk_st_bl_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_wlf/gcam_wlf_s_atk_st_bl_02.cani"},recoverPreOrientation=false,isEnableAtAnyCameras=true,keepPosition=false})
  table.insert(cameraAnimationFilePaths, {name="WolfAttackCrawlFront",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_wlf/gcam_wlf_c_atk_st_fl_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_wlf/gcam_wlf_c_atk_st_fl_02.cani"},recoverPreOrientation=false,isEnableAtAnyCameras=true,keepPosition=false})
  table.insert(cameraAnimationFilePaths, {name="WolfAttackCrawlBack",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_wlf/gcam_wlf_c_atk_st_bl_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_wlf/gcam_wlf_c_atk_st_bl_02.cani"},recoverPreOrientation=false,isEnableAtAnyCameras=true,keepPosition=false})
end

if not NCAESettings.nukeAnimation_pickupObjects then
  table.insert(cameraAnimationFilePaths, {name="PazPhantomPainPassPhotos",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_paz/gcam_paz_give_pic_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_paz/gcam_paz_give_pic_02.cani"},recoverPreOrientation=false,isEnableAtAnyCameras=true,ignoreCollisionCheckOnStart=true,ignoreCollisionCheckOnPlaying=true,keepPosition=true})
  table.insert(cameraAnimationFilePaths, {name="PazPhantomPainPickUpBook",filePath={"/Assets/tpp/motion/SI_game/fani/cameras/gcam_paz/gcam_paz_give_book_01.cani","/Assets/tpp/motion/SI_game/fani/cameras/gcam_paz/gcam_paz_give_book_02.cani"},recoverPreOrientation=false,isEnableAtAnyCameras=true,ignoreCollisionCheckOnStart=true,ignoreCollisionCheckOnPlaying=true,keepPosition=true})
end

Player.RegisterCameraAnimationFilePaths(cameraAnimationFilePaths)